kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: guestbook-1
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guestbook-1
            port:
              number: 8080
